var zetta = require('zetta')
var door = require('./mock_door.js')
var light = require('./mock_light_bulb.js')
var motionSensor = require('./mock_motion_sensor.js')
var tempSensor = require('./mock_temp_sensor.js')
var thermostat = require('./mock_thermostat.js')
var senseTemp = require('./senseTemparture.js')
var washingMachine = require('./mock_washing_machine.js')
var dishWasher = require('./mock_dish_washer.js')

zetta()
  .name('apigee_home')
  .use(door, 'living-room-door')
  .use(door, 'dining-room-door')
  .use(door, 'bed-room-door')
  .use(door, 'office-room-door')
  .use(door, 'bath-room-door')
  .use(light, 'living-room-bulb')
  .use(light, 'dining-room-bulb')
  .use(light, 'bed-room-bulb')
  .use(light, 'office-room-bulb')
  .use(light, 'bath-room-bulb')
  .use(motionSensor)
  .use(tempSensor)
  .use(thermostat)
  .use(senseTemp)
  .use(washingMachine)
  .use(dishWasher)
  .listen(process.env.PORT || 1337, function() {
    console.log('Apigee Link Home Server Started...')
  })